version=0.1

[default.deploy.parameters]
stack_name = "see-aws-infrastructure"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
s3_bucket = "see-aws-awscli-managed-default-samsourcebucket"
image_repositories = []